project:
  type: website
  output-dir: docs

website:
  title: "xnonaka.github.io"
  navbar:
    right:
      - text: "Data Viz"
        menu:
          - text: "Water Insecurity"
            href: waterinsecurity.qmd
          - text: "Highway Traffic"
            href: traffic.qmd
      - text: "Shakespeare Text Analysis"
        href: project2.qmd
      - text: "Penguin Permutation"
        href: project3.qmd
      - text: "Data Ethics"
        href: project4.qmd
      - text: "Traffic Stop Data"
        href: project5.qmd
      - text: "Final Presentation"
        href: DSPres.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

