project:
  type: website
  output-dir: docs

website:
  title: "xnonaka.github.io"
  navbar:
    right:
      - text: "About Me"
        href: about.qmd
      - text: "Data Viz"
        menu:
          - text: "Water Insecurity"
            href: waterinsecurity.qmd
          - text: "Highway Traffic"
            href: traffic.qmd
          - text: "Shakespeare Text"
            href: project2.qmd
          - text: "Penguin Permutation"
            href: project3.qmd
          - text: "Data Ethics"
            href: project4.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

